In [1]:
import pandas as pd
import numpy as np

In [2]:
# This will tell us the columns we are predicting
pred_cols = ['reactivity', 'deg_Mg_pH10', 'deg_pH10', 'deg_Mg_50C', 'deg_50C']

In [3]:
SEED = 2020

# 1

In [4]:
sub1 = pd.read_csv('./submission_bpps_large_attention_relu_dense_2020_0.csv')
sub2 = pd.read_csv('./submission_bpps_large_attention_relu_dense_2020_1.csv')
sub3 = pd.read_csv('./submission_bpps_large_attention_relu_dense_2020_2.csv')
sub4 = pd.read_csv('./submission_bpps_large_attention_relu_dense_2020_3.csv')
sub5 = pd.read_csv('./submission_bpps_large_attention_relu_dense_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_bpps_large_attention_relu_dense_2020_5fold.csv', index=False)

In [5]:
sub1 = pd.read_csv('./submission_bpps_large_attention_relu_dense_815_0.csv')
sub2 = pd.read_csv('./submission_bpps_large_attention_relu_dense_815_1.csv')
sub3 = pd.read_csv('./submission_bpps_large_attention_relu_dense_815_2.csv')
sub4 = pd.read_csv('./submission_bpps_large_attention_relu_dense_815_3.csv')
sub5 = pd.read_csv('./submission_bpps_large_attention_relu_dense_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_bpps_large_attention_relu_dense_815_5fold.csv', index=False)

# 2

In [6]:
sub1 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_0.csv')
sub2 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_1.csv')
sub3 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_2.csv')
sub4 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_3.csv')
sub5 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_5fold.csv', index=False)

In [7]:
sub1 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_0.csv')
sub2 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_1.csv')
sub3 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_2.csv')
sub4 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_3.csv')
sub5 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_5fold.csv', index=False)

# 3

In [8]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_5fold.csv', index=False)

In [9]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_5fold.csv', index=False)

# 4

In [10]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_5fold.csv', index=False)

In [11]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_5fold.csv', index=False)

# 5

In [12]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_5fold.csv', index=False)

In [13]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_5fold.csv', index=False)

# 6

In [14]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_5fold.csv', index=False)

In [15]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_5fold.csv', index=False)

# 7

In [16]:
sub1 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_0.csv')
sub2 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_1.csv')
sub3 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_2.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_3.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_5fold.csv', index=False)

In [17]:
sub1 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_0.csv')
sub2 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_1.csv')
sub3 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_2.csv')
sub4 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_3.csv')
sub5 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_4.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/5) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + sub5[pred_cols].values)

new_sub.to_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_5fold.csv', index=False)

# Ensemble7_2020

In [18]:
sub1 = pd.read_csv('./submission_bpps_large_attention_relu_dense_2020_5fold.csv')
sub2 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_2020_5fold.csv')
sub3 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_2020_5fold.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_2020_5fold.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_2020_5fold.csv') #25513
sub6 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_2020_5fold.csv') #25610
sub7 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_2020_5fold.csv') # 25755

new_sub = sub1.copy()

new_sub[pred_cols] = (1/7) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + \
                             sub5[pred_cols].values + sub6[pred_cols].values + sub7[pred_cols].values)

new_sub.to_csv('./ensemble_v7_2020.csv', index=False)

In [19]:
sub1 = pd.read_csv('./submission_bpps_large_attention_relu_dense_815_5fold.csv')
sub2 = pd.read_csv('./submission_bpps_large_lstm_gru_gru_newloss_815_5fold.csv')
sub3 = pd.read_csv('./tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_815_5fold.csv')
sub4 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_attention_relu_newloss_815_5fold.csv')
sub5 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_815_5fold.csv') #25513
sub6 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_newStruc_815_5fold.csv') #25610
sub7 = pd.read_csv('./submission_tf_simple_lstm_large_noise_more_epochs_bpps_large_new_loss_transformer_threeEmbedding_gru_twoloss_posEnc_BeforeConcat_815_5fold.csv') # 25755

new_sub = sub1.copy()

new_sub[pred_cols] = (1/7) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values + sub4[pred_cols].values + \
                             sub5[pred_cols].values + sub6[pred_cols].values + sub7[pred_cols].values)

new_sub.to_csv('./ensemble_v7_815.csv', index=False)

In [20]:
sub1 = pd.read_csv('./ensemble_v7.csv')
sub2 = pd.read_csv('./ensemble_v7_2020.csv')
sub3 = pd.read_csv('./ensemble_v7_815.csv')

new_sub = sub1.copy()

new_sub[pred_cols] = (1/3) * (sub1[pred_cols].values + sub2[pred_cols].values + sub3[pred_cols].values)

new_sub.to_csv('./ensemble_v7_42_2020_815.csv', index=False)

In [21]:
best = pd.read_csv('./ensemble_v7.csv')

In [22]:
np.corrcoef(best[pred_cols[0]], new_sub[pred_cols[0]])

array([[1.        , 0.99935954],
       [0.99935954, 1.        ]])

In [23]:
np.corrcoef(best[pred_cols[1]], new_sub[pred_cols[1]])

array([[1.        , 0.99933153],
       [0.99933153, 1.        ]])

In [24]:
np.corrcoef(best[pred_cols[2]], new_sub[pred_cols[2]])

array([[1.        , 0.99937119],
       [0.99937119, 1.        ]])

In [25]:
np.corrcoef(best[pred_cols[3]], new_sub[pred_cols[3]])

array([[1.        , 0.99940264],
       [0.99940264, 1.        ]])

In [26]:
best.head()

id_seqpos  reactivity  deg_Mg_pH10  deg_pH10  deg_Mg_50C   deg_50C
0  id_00073f8be_0    0.869267     0.657843  2.040880    0.544500  0.789857
1  id_00073f8be_1    2.320747     3.411660  3.982939    3.212782  2.778019
2  id_00073f8be_2    1.705457     0.707715  0.730908    0.795266  0.675442
3  id_00073f8be_3    1.294310     1.173735  1.231078    1.625431  1.878171
4  id_00073f8be_4    0.789423     0.554897  0.508882    0.815670  0.878281

In [27]:
new_sub.head()

id_seqpos  reactivity  deg_Mg_pH10  deg_pH10  deg_Mg_50C   deg_50C
0  id_00073f8be_0    0.863907     0.630919  2.017569    0.558756  0.790366
1  id_00073f8be_1    2.351414     3.394688  3.957128    3.183696  2.756634
2  id_00073f8be_2    1.686853     0.687740  0.730113    0.783540  0.671883
3  id_00073f8be_3    1.315491     1.166142  1.238855    1.623494  1.909643
4  id_00073f8be_4    0.787645     0.557079  0.509155    0.810845  0.864316